feat: [sc-63] Logout
bridge-agh/bridge-front pull request #4
Opened 2023-06-14 19:40 UTC by Carbon225

Story details: https://app.shortcut.com/bridge-agh/story/63

2023-06-14 19:41 UTC, Carbon225 commented
Depends on #1

2023-06-16 10:47 UTC, kappa243 reviewed
Czy po wylogowaniu ma się dostęp do protected route? Jeżeli nie to przydałby się redirect na stronę główną.

2023-06-16 10:58 UTC, Carbon225 commented
@kappa243
ProtectedRoute powinien automatycznie przekierować na /login po wylogowaniu ale dodałem redirect na /

2023-06-16 10:59 UTC, Carbon225 commented
@kappa243 pytanie
Czy w `components/root/drawer/drawer.tsx`
```typescript
export default function Drawer({ children }: { children: React.ReactNode }) {
  return (
    <div className="drawer drawer-end">
      <input id="drawer-menu" type="checkbox" className="drawer-toggle" />
      <div className="drawer-content">{children}</div>
      <div className="drawer-side hidden">
        <label className="drawer-overlay h-auto"></label>
        <ul className="menu p-4 w-full bg-base-100 gap-2">
          <li>
            <button className="btn uppercase text-neutral-content">
              Register
            </button>
          </li>
          <li>
            <button className="btn btn-primary uppercase text-primary-content">
              Log in
            </button>
          </li>
          <div className="flex-1 flex flex-col justify-end">
            <li>
              <ThemeSwitch className="btn text-neutral-content" />
            </li>
          </div>
        </ul>
      </div>
    </div>
  );
}
```
muszę coś zmienić?
Te buttony?

2023-06-16 11:03 UTC, kappa243 commented
@Carbon225 Tak, tam jest osobna struktura buttonów. Myślę, że przydałoby się tam to pozmieniać jeżeli robimy mobile first.

2023-06-16 11:44 UTC, Carbon225 commented
@kappa243 poprawiłem drawer

2023-06-16 17:28 UTC, kappa243 requested changes

2023-06-16 17:28 UTC, kappa243 commented on src/components/root/header/header.tsx
> +          <div>{user.email}</div>
Na sm/md nachodzi na wszystko

2023-06-16 21:29 UTC, Carbon225 commented on src/components/root/header/header.tsx
> +          <div>{user.email}</div>
Chciałbym tam mieć jakiś display name ale jeszcze nie mamy takiego czegoś.
Widzisz jakieś rozwiązanie?

2023-06-16 21:29 UTC, Carbon225 commented on src/components/root/header/header.tsx
> +          <div>{user.email}</div>
regex łapiący wszystko przed @?

2023-06-16 22:01 UTC, kappa243 commented on src/components/root/header/header.tsx
> +          <div>{user.email}</div>
chyba username podajemy

2023-06-16 22:07 UTC, Carbon225 commented on src/components/root/header/header.tsx
> +          <div>{user.email}</div>
Firebase nie ma czegoś takiego. Trzeba ręcznie zaimplementować z firestore.

2023-06-16 22:22 UTC, kappa243 commented on src/components/root/header/header.tsx
> +          <div>{user.email}</div>
proponuje zostawić tak w wersji zabugowanej i zrobimy osobne story od tego

2023-06-16 22:43 UTC, Carbon225 commented on src/components/root/header/header.tsx
> +          <div>{user.email}</div>
+1

2023-06-16 23:05 UTC, kappa243 approved these changes

2023-06-16 23:06 UTC, merged