fix: [sc-86] Status fix
bridge-agh/bridge-front pull request #9
Opened 2023-06-21 16:30 UTC by kappa243

Story details: https://app.shortcut.com/bridge-agh/story/86

2023-06-21 16:38 UTC, Carbon225 requested changes

2023-06-21 16:38 UTC, Carbon225 commented on src/app/login/loginForm.tsx
> +      router.replace("/home");
Dlaczego w useEffect? Nie widzę czemu nie ale czy jest jakiś powód?

2023-06-21 16:38 UTC, Carbon225 commented on src/components/protected_route.tsx
> +    router.prefetch("/login");
Myślę że to powinno mieć własny useEffect bo jest całkowite niezwiązane z resztą tego effectu i niepotrzebnie wykonuje się wiele razy.

2023-06-21 16:38 UTC, Carbon225 commented on src/components/protected_route.tsx
> +  return (
Bardziej przejrzysta była poprzednia logika a nie wszystko wpakowane do JSX.

2023-06-21 16:39 UTC, Carbon225 commented
Nie do końca widzę co robi ładowanie tych routerów do useEffect.

2023-06-21 18:40 UTC, kappa243 commented
> Nie do końca widzę co robi ładowanie tych routerów do useEffect.

Wszystko to żeby zlikwidować warning:
![image](https://github.com/bridge-agh/bridge-front/assets/17147479/41bac49e-af0c-4ba5-81fe-7ec8dea64aa3)

Możesz to zreplikować tak:

1. Ładujesz główną stronę - /
2. Wchodzisz na /home linkiem z debug page i wywala error
3. Logujesz się i przekierowuje cię do /home i wywala error (tym razem z LoginForm)

2023-06-21 19:52 UTC, Carbon225 commented
To możesz tylko wyciągnąć preloady do osobnych efektów i przepisać logikę protected route bo serio mi się nie podoba. Albo wrócić jak było bo chyba logicznie nie zmieniałeś.

2023-06-22 20:45 UTC, Carbon225 approved these changes

2023-06-22 20:45 UTC, Carbon225 commented
@kappa243 zerknij

2023-06-22 21:13 UTC, karolsliwa reviewed
Zdaję się że wszystko git, działa dobrze

2023-06-23 01:18 UTC, merged